import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {matrixToB08Rows,readB08File,importarB08,normalizeB08Row,aplicarFotografiaReal} from '../js/b08-service.js';

const header=['VOLUME','PEDIDO','ITEM','CLIENTE','EQUIPE','BENEFICIADOR','FERRAMENTA','PEÇAS','PESO LÍQUIDO','BENEFICIAMENTO','DATA'];
const record=['V-001','PV-10','20','PRADO','A','01533','EIR-033','144','272,50','BRANCO RAL 9003','20/09/2026'];
const REAL_HEADERS=['VOLUME_ID','PEDIDO_ID','ITEM','ID','CODIGO','TRATAMENTO','SINAL','PROCESSO_ID','TIPO','STATUS','DATA','EQUIPE','FERRAMENTA_ID','AMARRADOS','PECAS','PESOLIQUIDO','PESOBRUTO','QTDE','QTATENDIDO','SL_PECAS','PCATENDIDO','LIGA','TEMPERA','COMPRIMENTO','BENEFICIAMENTO','ENTREGA','ENVIA_CA','ATD_UNIDADE','QTDE_EXATA','TRANSPORTADORA_ID','BENEFICIADOR_ID','TRANSPORTADORA','BENEFICIADOR','BF_TRATAMENTO','SAIDA_ID','EMISSAO','TRA_TRATAMENTO','TRA_BAIRRO','BFN_TRATAMENTO','BFN_BAIRRO','INTENCAO','VALOR','RESERVA_ID','RESERVA_ITEM','RESERVA_DATA','GRAMATURAL','GRAMATURAF','FILIAL','BF_DATA','RETORNO_BENEF','OBSERVACAO','LIBERADO'];
const realRecord=(i,benef='01533',equipe='A')=>{const data={VOLUME_ID:88000+i,PEDIDO_ID:12966,ITEM:8,ID:'CL',CODIGO:'00197',TRATAMENTO:'    AELSON TAVARES',SINAL:1,PROCESSO_ID:0,TIPO:1,STATUS:'0',DATA:45555,EQUIPE:equipe,FERRAMENTA_ID:'E25-177',AMARRADOS:12,PECAS:'144',PESOLIQUIDO:'272,00',PESOBRUTO:272,QTDE:400,QTATENDIDO:0,SL_PECAS:207,PCATENDIDO:0,LIGA:'6060',TEMPERA:'T5',COMPRIMENTO:6000,BENEFICIAMENTO:'PPF05',ENTREGA:45530,ENVIA_CA:'N',ATD_UNIDADE:0,QTDE_EXATA:'N',TRANSPORTADORA_ID:'CL',BENEFICIADOR_ID:'CL',TRANSPORTADORA:'00197',BENEFICIADOR:benef,BF_TRATAMENTO:'',SAIDA_ID:'',EMISSAO:'',TRA_TRATAMENTO:'AELSON TAVARES',TRA_BAIRRO:'CENTRO',BFN_TRATAMENTO:'EXTRUCOLOR',BFN_BAIRRO:'JARDIM FATIMA',INTENCAO:'',VALOR:8840,RESERVA_ID:'',RESERVA_ITEM:'',RESERVA_DATA:'',GRAMATURAL:314,GRAMATURAF:322,FILIAL:'01',BF_DATA:'',RETORNO_BENEF:'N',OBSERVACAO:i%2?'':'TV: BAIXA VOLUMES',LIBERADO:1};return REAL_HEADERS.map(h=>data[h]??'');};

test('arquivo tabular válido reconhece a B08',()=>{const r=matrixToB08Rows([header,record]);assert.equal(r.rows.length,1);assert.equal(normalizeB08Row(r.rows[0]).volume,'V-001');});
test('arquivo vazio informa motivo',()=>assert.throws(()=>matrixToB08Rows([]),/Planilha vazia/));
test('cabeçalho pode estar fora da primeira linha',()=>{const r=matrixToB08Rows([['RELATÓRIO B08'],['Gerado em 20/09'],header,record]);assert.equal(r.headerRow,3);assert.equal(r.rows.length,1);});
test('colunas adicionais são toleradas',()=>{const r=matrixToB08Rows([[...header,'COLUNA EXTRA'],[...record,'qualquer valor']]);assert.equal(r.rows[0]['COLUNA EXTRA'],'qualquer valor');});
test('números armazenados como texto são convertidos',()=>{const [v]=matrixToB08Rows([header,record]).rows.map(normalizeB08Row);assert.equal(v.pecas,144);assert.equal(v.pesoLiquido,272.5);});
test('data serial do Excel é convertida',()=>{const line=[...record];line[10]=45555;const [row]=matrixToB08Rows([header,line]).rows;assert.match(row.DATA,/^2024-/);});
test('coluna VOLUME ausente gera erro compreensível',()=>assert.throws(()=>matrixToB08Rows([['PEDIDO','CLIENTE'],['1','PRADO']]),/coluna VOLUME/));
test('registros duplicados não são recriados',()=>{const rows=matrixToB08Rows([header,record]).rows,a=importarB08([],rows),b=importarB08(a.volumes,rows);assert.equal(b.volumes.length,1);assert.equal(b.stats.conhecidos,1);});
test('beneficiador diferente não entra na Pintura',()=>{const line=[...record];line[5]='002000';const r=importarB08([],matrixToB08Rows([header,line]).rows);assert.equal(r.stats.pintura,0);assert.equal(r.stats.ignorados,1);});
test('erro de leitura do arquivo não fica silencioso',async()=>{const file={name:'B08.xlsx',arrayBuffer:async()=>{throw new Error('arquivo corrompido');}};await assert.rejects(()=>readB08File(file,{read(){},utils:{sheet_to_json(){}}}),/Erro ao processar arquivo: arquivo corrompido/);});
test('CSV também aceita linhas antes do cabeçalho',async()=>{const csv=`RELATÓRIO B08;;;;;;;;;;\n${header.join(';')}\n${record.join(';')}`;const r=await readB08File({name:'B08.csv',text:async()=>csv});assert.equal(r.headerRow,2);assert.equal(r.rows.length,1);});

test('XLSX realista é escrito e lido pelo leitor embarcado',async()=>{
 const code=readFileSync(new URL('../vendor/xlsx.full.min.js',import.meta.url),'utf8'),sandbox={exports:{},module:{exports:{}},console,process};sandbox.global=sandbox;sandbox.globalThis=sandbox;vm.runInNewContext(code,sandbox);const XLSX=Object.keys(sandbox.module.exports).length?sandbox.module.exports:sandbox.exports;
 const sheet=XLSX.utils.aoa_to_sheet([['Extrutech - Embalagem da Extrusão'],[],header,record]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,'B08 Disponível');const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'});
 const parsed=await readB08File({name:'B08.xlsx',arrayBuffer:async()=>bytes},XLSX);assert.equal(parsed.sheetName,'B08 Disponível');assert.equal(parsed.headerRow,3);assert.equal(normalizeB08Row(parsed.rows[0]).beneficiador,'01533');
});

test('layout real AceManager reconhece 190 linhas e 52 colunas',()=>{const data=Array.from({length:187},(_,i)=>realRecord(i+1,i<79?'01533':'01325',i<26?'A':'P')),parsed=matrixToB08Rows([['Volumes para Embarque'],['Semana Corrente'],REAL_HEADERS,...data]);assert.equal(parsed.physicalRows,190);assert.equal(parsed.headers.length,52);assert.equal(parsed.headerRow,3);assert.equal(parsed.rows.length,187);});
test('mapeamento real preserva BENEFICIADOR_ID e BENEFICIADOR sem confundir',()=>{const v=normalizeB08Row(matrixToB08Rows([REAL_HEADERS,realRecord(1)]).rows[0]);assert.equal(v.beneficiadorIdOriginal,'CL');assert.equal(v.beneficiadorOriginal,'01533');assert.equal(v.beneficiador,'01533');assert.equal(v.beneficiadorFonte,'BENEFICIADOR');});
test('layout real mapeia campos operacionais e de auditoria',()=>{const v=normalizeB08Row(matrixToB08Rows([REAL_HEADERS,realRecord(1)]).rows[0]);assert.deepEqual([v.volume,v.pedido,v.item,v.cliente,v.equipe,v.ferramenta,v.amarrados,v.pecas,v.pesoLiquido,v.pesoBruto,v.liga,v.tempera,v.comprimento,v.beneficiamento],['88001','12966','8','AELSON TAVARES','A','E25-177',12,144,272,272,'6060','T5','6000','PPF05']);assert.equal(v.camposOriginais.BENEFICIADOR_ID,'CL');});
test('regra preserva valor literal e aceita somente 01533',()=>{for(const code of['1533','01533','001533']){const row=Object.fromEntries(REAL_HEADERS.map((h,i)=>[h,realRecord(1,code)[i]])),v=normalizeB08Row(row);assert.equal(v.beneficiador,code);assert.equal(v.beneficiador==='01533',code==='01533');}});
test('contagem realista identifica universo Pintura e equipes A/P',()=>{const rows=Array.from({length:187},(_,i)=>realRecord(i+1,i<79?'01533':'01325',i<26?'A':i<79?'P':'A')),parsed=matrixToB08Rows([['Volumes para Embarque'],['Semana Corrente'],REAL_HEADERS,...rows]),result=importarB08([],parsed.rows);assert.equal(result.stats.totalLidos,187);assert.equal(result.stats.pintura,79);assert.equal(result.stats.equipeA,26);assert.equal(result.stats.equipeP,53);assert.equal(result.stats.ignorados,108);});
test('primeira B08 real substitui a demonstração sem misturar dados',()=>{const rows=matrixToB08Rows([REAL_HEADERS,realRecord(1)]).rows,base={modoDados:'simulados',volumes:[{volume:'DEMO-1'}],lotes:[{id:'L-DEMO'}],eventos:[{id:'E-DEMO'}],programacoes:[{id:'P-DEMO'}],importacoes:[{arquivo:'SIMULADA'}]},r=aplicarFotografiaReal(base,rows,'2026-09-21T08:00:00.000Z');assert.equal(r.db.modoDados,'real');assert.deepEqual(r.db.volumes.map(v=>v.volume),['88001']);assert.deepEqual([r.db.lotes.length,r.db.eventos.length,r.db.programacoes.length,r.db.importacoes.length],[0,0,0,0]);});
test('fotografias reais seguintes preservam operação e atualizam volumes',()=>{const rows=matrixToB08Rows([REAL_HEADERS,realRecord(1)]).rows,base={modoDados:'real',volumes:[],lotes:[{id:'L-REAL'}],eventos:[{id:'E-REAL'}],programacoes:[{id:'P-REAL'}],importacoes:[{arquivo:'B08-ANTERIOR'}]},r=aplicarFotografiaReal(base,rows,'2026-09-21T08:00:00.000Z');assert.equal(r.db.volumes.length,1);assert.deepEqual([r.db.lotes.length,r.db.eventos.length,r.db.programacoes.length,r.db.importacoes.length],[1,1,1,1]);});
test('ordem diferente e coluna extra não alteram o mapeamento',()=>{const reordered=['COLUNA_EXTRA',...REAL_HEADERS.slice().reverse()],base=Object.fromEntries(REAL_HEADERS.map((h,i)=>[h,realRecord(1)[i]])),line=reordered.map(h=>h==='COLUNA_EXTRA'?'extra':base[h]);const v=normalizeB08Row(matrixToB08Rows([reordered,line]).rows[0]);assert.equal(v.volume,'88001');assert.equal(v.beneficiador,'01533');assert.equal(v.equipe,'A');});
