import test from'node:test';import assert from'node:assert/strict';
import{normalizeB08Row,importarB08,parseCsv,pertencePintura,interpretarEquipe,chaveMaterial}from'../js/b08-service.js';
import{formarLote,registrarRecebimento,iniciarProcesso,finalizarEmbalagem,temposLote}from'../js/model.js';
import{agruparPorCliente,agruparPorPedido,agruparPorCor,filaPintura,indicadores,toneladas,statusConfronto}from'../js/analytics.js';
import{menuTransition,isMobileWidth}from'../js/ui-state.js';import{createMockData,B08_ROWS,USERS}from'../js/mock-data.js';
const T={t0:'2026-09-20T07:00:00.000Z',rec:'2026-09-20T08:00:00.000Z',ini:'2026-09-20T08:15:00.000Z',fim:'2026-09-20T14:45:00.000Z'};
const imported=()=>importarB08([],B08_ROWS,T.t0);const queue=()=>imported().volumes.filter(v=>v.equipe==='A');const formed=()=>formarLote(queue().slice(0,2),{numero:'PNT-T',prioridade:'Alta'},USERS.pcp,T.t0);
test('normaliza e preserva volume B08',()=>assert.equal(normalizeB08Row(B08_ROWS[0]).volume,'A1001'));
test('normaliza beneficiador 00153',()=>assert.equal(normalizeB08Row(B08_ROWS[0]).beneficiador,'00153'));
test('filtro aceita beneficiador da Pintura',()=>assert.equal(pertencePintura(normalizeB08Row(B08_ROWS[0])),true));
test('filtro exclui beneficiador diferente',()=>assert.equal(pertencePintura(normalizeB08Row(B08_ROWS.at(-1))),false));
test('Equipe A vira fila da Pintura',()=>assert.equal(interpretarEquipe({equipe:'A'}),'FILA_PINTURA'));
test('Equipe P vira evidência de pintado',()=>assert.equal(interpretarEquipe({equipe:'P'}),'PINTADO_ACESYS'));
test('importação contabiliza arquivo completo',()=>assert.equal(imported().stats.totalLidos,B08_ROWS.length));
test('importação informa ignorados',()=>assert.equal(imported().stats.ignorados,1));
test('material natural não entra no universo operacional',()=>assert.ok(!imported().volumes.some(v=>v.volume==='N9001')));
test('reimportação não duplica volumes',()=>{const a=imported(),b=importarB08(a.volumes,B08_ROWS,T.rec);assert.equal(b.volumes.length,a.volumes.length);assert.equal(b.stats.conhecidos,a.volumes.length);});
test('fotografia diária atualiza registro conhecido',()=>{const a=imported(),changed={...B08_ROWS[0],PEÇAS:'145'},b=importarB08(a.volumes,[changed],T.rec);assert.equal(b.volumes.find(v=>v.volume==='A1001').pecas,145);assert.equal(b.stats.atualizados,1);});
test('atualização preserva histórico B08',()=>{const a=imported(),b=importarB08(a.volumes,[{...B08_ROWS[0],PEÇAS:'145'}],T.rec);assert.equal(b.volumes.find(v=>v.volume==='A1001').historicoB08.length,2);});
test('P confirma A pela chave material',()=>assert.equal(imported().volumes.find(v=>v.volume==='A1020').confirmadoAcesys,true));
test('chave material independe do volume',()=>assert.equal(chaveMaterial(normalizeB08Row(B08_ROWS[4])),chaveMaterial(normalizeB08Row(B08_ROWS[5]))));
test('parser CSV reconhece beneficiador',()=>{const [r]=parseCsv('VOLUME;BENEFICIADOR;EQUIPE;PESO LÍQUIDO\n1;00153;A;12,50');assert.equal(normalizeB08Row(r).pesoLiquido,12.5);});
test('fila contém somente 00153 Equipe A não confirmado',()=>assert.ok(filaPintura(imported().volumes).every(v=>v.beneficiador==='00153'&&v.equipe==='A'&&!v.confirmadoAcesys)));
test('forma lote e preserva volumes individuais',()=>assert.equal(formed().lote.volumeIds.length,2));
test('soma peças do lote',()=>assert.equal(formed().lote.pecasB08,256));
test('soma kg do lote',()=>assert.equal(formed().lote.kgB08,638.5));
test('bloqueia formação com Equipe P',()=>assert.throws(()=>formarLote([imported().volumes.find(v=>v.equipe==='P')],{},USERS.pcp),/EQUIPE A/));
test('recebimento divergente exige motivo',()=>assert.throws(()=>registrarRecebimento(formed().lote,{quantidadeVolumes:2,pecas:250,kg:638.5},USERS.recebimento,T.rec),/motivo/));
test('recebimento registra usuário e timestamp',()=>{const r=registrarRecebimento(formed().lote,{quantidadeVolumes:2,pecas:256,kg:638.5},USERS.recebimento,T.rec);assert.equal(r.evento.usuario.nome,USERS.recebimento.nome);assert.equal(r.lote.recebidoEm,T.rec);});
const processing=()=>{let l=registrarRecebimento(formed().lote,{quantidadeVolumes:2,pecas:256,kg:638.5},USERS.recebimento,T.rec).lote;return iniciarProcesso(l,{pecas:256,kg:638.5},USERS.operador,T.ini).lote;};
test('finalização exige fechamento de peças',()=>assert.throws(()=>finalizarEmbalagem(processing(),{pecasBoas:250,kg:620,perda:1,retrabalho:1,divergencia:0,motivo:'x'},USERS.embalagem,T.fim),/conta deve fechar/));
test('perda e retrabalho exigem motivo',()=>assert.throws(()=>finalizarEmbalagem(processing(),{pecasBoas:250,kg:620,perda:4,retrabalho:2,divergencia:0,motivo:''},USERS.embalagem,T.fim),/motivo/));
test('histórico operacional é append-only',()=>{const f=formed(),r=registrarRecebimento(f.lote,{quantidadeVolumes:2,pecas:256,kg:638.5},USERS.recebimento,T.rec);assert.notEqual(f.evento.id,r.evento.id);assert.equal(f.evento.tipo,'formacao');});
test('tempo de processo é calculado',()=>assert.equal(temposLote({recebidoEm:T.rec,inicioProcessoEm:T.ini,finalizadoEm:T.fim}).processoMs,6.5*3600000));
test('APP finalizado + B08 A aguarda confirmação',()=>{const f={...formed().lote,etapaAtual:'finalizado'},vs=queue().slice(0,2).map(v=>({...v,confirmadoAcesys:false}));f.volumeIds=vs.map(v=>v.id);assert.equal(statusConfronto(f,vs),'AGUARDANDO_B08');});
test('APP finalizado + B08 P fica confirmado',()=>{const f={...formed().lote,etapaAtual:'finalizado'},vs=queue().slice(0,2).map(v=>({...v,confirmadoAcesys:true}));f.volumeIds=vs.map(v=>v.id);assert.equal(statusConfronto(f,vs),'CONFIRMADO_ACESYS');});
test('B08 P + APP não finalizado é divergência',()=>{const f={...formed().lote,etapaAtual:'processo'},vs=queue().slice(0,2).map(v=>({...v,confirmadoAcesys:true}));f.volumeIds=vs.map(v=>v.id);assert.equal(statusConfronto(f,vs),'DIVERGENCIA_B08_SEM_APP');});
test('agrupa por cliente',()=>assert.ok(agruparPorCliente(filaPintura(imported().volumes)).some(g=>g.chave==='PRADO')));
test('agrupa por pedido',()=>assert.ok(agruparPorPedido(filaPintura(imported().volumes)).some(g=>g.chave==='PV-8431')));
test('agrupa por cor',()=>assert.ok(agruparPorCor(filaPintura(imported().volumes)).some(g=>g.chave==='BRANCO RAL 9003')));
test('soma kg por cliente corretamente',()=>assert.equal(agruparPorCliente(filaPintura(imported().volumes)).find(g=>g.chave==='PRADO').kg,1369.5));
test('soma kg por cor corretamente',()=>assert.equal(agruparPorCor(filaPintura(imported().volumes)).find(g=>g.chave==='PRETO RAL 9005').kg,1150));
test('converte kg para toneladas',()=>assert.equal(toneladas(4850),4.85));
test('indicadores calculam fila pendente',()=>{const db=createMockData(),i=indicadores(db.volumes,db.lotes);assert.ok(i.programado>i.fila);assert.ok(i.processo>0);});
test('mock cobre três cenários APP x ACESYS',()=>{const db=createMockData(),s=new Set(db.lotes.map(l=>statusConfronto(l,db.volumes)));assert.ok(s.has('AGUARDANDO_B08'));assert.ok(s.has('CONFIRMADO_ACESYS'));assert.ok(s.has('DIVERGENCIA_B08_SEM_APP'));});
for(const width of[360,390,412,430])test(`menu inicia recolhido em ${width}px`,()=>{assert.equal(isMobileWidth(width),true);assert.equal(menuTransition(false,'outside',true),false);});
test('menu mobile alterna, fecha fora e após navegar',()=>{assert.equal(menuTransition(false,'toggle',true),true);assert.equal(menuTransition(true,'outside',true),false);assert.equal(menuTransition(true,'navigate',true),false);});
test('desktop não mantém estado de overlay mobile',()=>assert.equal(menuTransition(true,'toggle',false),false));
