import test from'node:test';import assert from'node:assert/strict';
import{createMockData,USERS}from'../js/mock-data.js';
import{blocosDisponiveis,criarProgramacao,adicionarBloco,moverBloco,removerBloco,vincularLote,resumoProgramacao,resumoCarteira,blocoKey}from'../js/programming-service.js';
const now='2026-09-21T08:00:00.000Z';
const seed=()=>createMockData();
const setup=()=>{const db=seed(),p=criarProgramacao({data:'2026-09-21',turno:'DIA'},USERS.pcp,now),available=blocosDisponiveis(db.volumes,[]);return{db,p,available};};
test('cria programação por data',()=>assert.equal(setup().p.data,'2026-09-21'));
test('cria programação por turno',()=>assert.equal(setup().p.turno,'DIA'));
test('rejeita turno desconhecido',()=>assert.throws(()=>criarProgramacao({data:'2026-09-21',turno:'TARDE'},USERS.pcp),/Dia ou Noite/));
test('bloco disponível combina cliente e cor',()=>{const b=setup().available[0];assert.equal(b.key,blocoKey(b.cliente,b.cor));});
test('mesmo cliente pode aparecer em cores diferentes',()=>{const s=setup(),base=s.db.volumes.find(v=>v.equipe==='A'),extra={...base,id:'B08-EXTRA',volume:'EXTRA',beneficiamento:'COR-EXTRA',loteId:null};const bs=blocosDisponiveis([...s.db.volumes,extra],[]).filter(b=>b.cliente===base.cliente);assert.ok(new Set(bs.map(b=>b.cor)).size>1);});
test('adiciona bloco à sequência',()=>{const{x:p,}= {x:setup().p};const b=setup().available[0],n=adicionarBloco(p,b,USERS.pcp,now);assert.equal(n.blocos.length,1);});
test('ordena blocos automaticamente',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),b=adicionarBloco(a,s.available[1],USERS.pcp);assert.deepEqual(b.blocos.map(x=>x.ordem),[1,2]);});
test('move bloco não iniciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),b=adicionarBloco(a,s.available[1],USERS.pcp),n=moverBloco(b,b.blocos[1].id,'subir',USERS.pcp);assert.equal(n.blocos[0].id,b.blocos[1].id);});
test('protege reordenação de bloco iniciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),locked=vincularLote(a,a.blocos[0].id,'LOT-1','recebido');assert.throws(()=>moverBloco(locked,locked.blocos[0].id,'descer',USERS.pcp),/iniciados/);});
test('remove bloco ainda não iniciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp);assert.equal(removerBloco(a,a.blocos[0].id,USERS.pcp).blocos.length,0);});
test('protege remoção de bloco iniciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),locked=vincularLote(a,a.blocos[0].id,'LOT-1','processo');assert.throws(()=>removerBloco(locked,locked.blocos[0].id,USERS.pcp),/iniciados/);});
test('recalcula kg total sequenciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp);assert.equal(resumoProgramacao(a).kg,s.available[0].kg);});
test('recalcula peças totais',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp);assert.equal(resumoProgramacao(a).pecas,s.available[0].pecas);});
test('recalcula kg por cor',()=>{const s=setup(),same=s.available.filter(x=>x.cor===s.available[0].cor),a=same.reduce((p,b)=>adicionarBloco(p,b,USERS.pcp),s.p);assert.equal(resumoProgramacao(a).porCor[0].kg,same.reduce((n,b)=>n+b.kg,0));});
test('percentuais por cor fecham cem',()=>{const s=setup(),a=adicionarBloco(adicionarBloco(s.p,s.available[0],USERS.pcp),s.available[1],USERS.pcp),total=resumoProgramacao(a).porCor.reduce((n,x)=>n+x.percentual,0);assert.ok(Math.abs(total-100)<0.01);});
test('separa disponível de sequenciado',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),r=resumoCarteira(s.db.volumes,[a]);assert.equal(r.sequenciado,s.available[0].kg);assert.equal(r.disponivel-r.sequenciado,r.naoSequenciado);});
test('bloco sequenciado sai das opções disponíveis',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),remaining=blocosDisponiveis(s.db.volumes,[a]);assert.ok(!remaining.some(b=>b.key===s.available[0].key));});
test('visão do líder usa a mesma ordem persistida pelo PCP',()=>{const s=setup(),a=adicionarBloco(adicionarBloco(s.p,s.available[0],USERS.pcp),s.available[1],USERS.pcp);assert.deepEqual(a.blocos.map(b=>b.ordem),[1,2]);});
test('vincula lote sem apagar histórico da programação',()=>{const s=setup(),a=adicionarBloco(s.p,s.available[0],USERS.pcp),n=vincularLote(a,a.blocos[0].id,'LOT-1','recebido');assert.equal(n.blocos[0].loteId,'LOT-1');assert.equal(n.historico.length,a.historico.length);});
test('capacidade calcula utilização sem bloquear excesso',()=>{const s=setup(),p={...s.p,capacidadeKg:100},a=adicionarBloco(p,s.available[0],USERS.pcp);assert.ok(resumoProgramacao(a).utilizacao>100);});
