import{ETAPAS,PRIORIDADES,STATUS_VOLUME,etapaLabel}from'./constants.js';
import{formarLote,registrarRecebimento,iniciarProcesso,finalizarEmbalagem,temposLote,progresso}from'./model.js';
import{importarB08,parseCsv}from'./b08-service.js';
import{LocalPinturaStore}from'./storage-service.js';
import{createMockData,USERS}from'./mock-data.js';
const store=new LocalPinturaStore(createMockData);let db=store.load();if(db.version!==2){localStorage.removeItem('extrutech.pintura.prototype.v1');db=store.load();}
let ui={view:'painel',selected:null,selectedVolumes:new Set(),modal:null,error:'',toast:'',importResult:null,filters:{busca:'',etapa:'todas',prioridade:'todas',situacao:'ativos',volStatus:'disponivel',data:''}};
const app=document.querySelector('#app'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),kg=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:3}),dt=i=>i?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(i)):'—',lot=id=>db.lotes.find(l=>l.id===id),events=id=>db.eventos.filter(e=>e.loteId===id).sort((a,b)=>new Date(b.criadoEm)-new Date(a.criadoEm)),fd=f=>Object.fromEntries(new FormData(f).entries());
function duration(ms){if(ms==null)return'—';const min=Math.round(ms/60000),h=Math.floor(min/60),m=min%60;return h?`${h}h${String(m).padStart(2,'0')}min`:`${m}min`;}
function save(msg){store.save(db);ui.toast=msg;render();setTimeout(()=>{ui.toast='';render();},2300);}
function render(){app.innerHTML=`${top()}<div class="layout">${side()}<main class="main">${page()}</main></div>${modal()}${ui.toast?`<div class="toast">${esc(ui.toast)}</div>`:''}`;bind();}
const nav=(id,icon,label,count='')=>`<button class="nav-btn ${ui.view===id?'active':''}" data-view="${id}"><span>${icon}&nbsp;&nbsp;${label}</span>${count!==''?`<span class="nav-count">${count}</span>`:''}</button>`;
function top(){return`<header class="topbar"><div class="brand"><div class="brand-mark">P</div><div><strong>Extrutech · Pintura</strong><small>B08 → lote → processo macro</small></div></div><div class="actor"><span class="actor-dot"></span><span>Protótipo local · sem Firebase</span></div></header>`;}
function side(){return`<aside class="sidebar"><div><div class="nav-title">Operação</div>${nav('painel','▦','Painel')}${nav('b08','▤','Materiais B08',db.volumes.filter(v=>v.status==='disponivel').length)}${nav('rastreio','⌕','Rastreamento',db.lotes.length)}${nav('finalizados','✓','Finalizados',db.lotes.filter(l=>l.status==='finalizado').length)}<div class="nav-title" style="margin-top:18px">Controle</div>${nav('divergencias','!','Divergências',db.eventos.filter(e=>e.perda||e.retrabalho||e.divergencia).length)}${nav('consumo','◉','Consumo de tinta')}<div class="side-note"><strong>Fluxo simplificado</strong><br>Recebido → Em processo → Embalagem finalizada.</div></div></aside>`;}
function head(title,sub,action=''){return`<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function page(){return({painel:dashboard,b08:b08Page,rastreio:tracking,finalizados:finished,divergencias:issues,consumo:consumption,detalhe:detail}[ui.view]||dashboard)();}
function stats(){const c=id=>db.lotes.filter(l=>l.etapaAtual===id).length;return`<div class="stats"><div class="stat"><div class="value">${db.volumes.filter(v=>v.status==='disponivel').length}</div><div class="label">Volumes B08 disponíveis</div></div><div class="stat"><div class="value">${c('recebido')}</div><div class="label">Recebidos na Pintura</div></div><div class="stat alert"><div class="value">${c('processo')}</div><div class="label">Em processo</div></div><div class="stat"><div class="value">${c('finalizado')}</div><div class="label">Embalagem finalizada</div></div><div class="stat alert"><div class="value">${db.lotes.filter(l=>l.prioridade==='Urgente'&&l.status==='ativo').length}</div><div class="label">Urgências</div></div><div class="stat"><div class="value">${db.lotes.reduce((s,l)=>s+l.perdasAcumuladas,0)}</div><div class="label">Perdas registradas</div></div></div>`;}
function dashboard(){return`${head('Painel da Pintura','Visão macro, da B08 à embalagem finalizada.','<button class="btn btn-primary" data-view="b08">Selecionar volumes B08</button>')}${stats()}<section class="panel"><div class="panel-head"><h2>Lotes ativos</h2><span class="muted mono">3 marcos operacionais</span></div>${lotList(db.lotes.filter(l=>l.status==='ativo'))}</section>`;}
function volFiltered(){const q=ui.filters.busca.toLowerCase();return db.volumes.filter(v=>(ui.filters.volStatus==='todos'||v.status===ui.filters.volStatus)&&(!ui.filters.data||v.dataEmbalagem===ui.filters.data)&&(!q||[v.volume,v.pedido,v.item,v.cliente,v.ferramenta,v.beneficiamento].join(' ').toLowerCase().includes(q)));}
function b08Page(){const vs=volFiltered(),sel=[...ui.selectedVolumes].map(id=>db.volumes.find(v=>v.id===id)).filter(Boolean),pieces=sel.reduce((s,v)=>s+v.pecas,0),weight=sel.reduce((s,v)=>s+v.pesoLiquido,0);return`${head('Materiais embalados · B08','Selecione volumes compatíveis para formar um lote de Pintura.','<button class="btn btn-secondary" data-action="import">Importar / atualizar B08</button>')}<section class="panel"><div class="toolbar"><input class="input" data-filter="busca" placeholder="Cliente, pedido, volume, perfil ou cor" value="${esc(ui.filters.busca)}"><select class="input" data-filter="volStatus"><option value="disponivel">Disponíveis</option><option value="vinculado" ${ui.filters.volStatus==='vinculado'?'selected':''}>Vinculados</option><option value="todos" ${ui.filters.volStatus==='todos'?'selected':''}>Todos</option></select><input class="input" data-filter="data" placeholder="Data embalagem" value="${esc(ui.filters.data)}"><div></div></div><div class="b08-table"><div class="b08-row b08-head"><span></span><span>Volume / pedido</span><span>Cliente / perfil</span><span>Beneficiamento</span><span>Quantidade</span><span>Status</span></div>${vs.map(v=>`<label class="b08-row"><input type="checkbox" data-volume="${v.id}" ${ui.selectedVolumes.has(v.id)?'checked':''} ${v.status!=='disponivel'?'disabled':''}><span><strong class="mono">${esc(v.volume)}</strong><small>${esc(v.pedido)} · item ${esc(v.item)}</small></span><span><strong>${esc(v.cliente)}</strong><small>${esc(v.ferramenta)} · ${esc(v.comprimento)} mm</small></span><span>${esc(v.beneficiamento)}<small>Emb. ${esc(v.dataEmbalagem)}</small></span><span><strong>${v.pecas} peças</strong><small>${kg(v.pesoLiquido)} kg</small></span><span class="tag ${v.status==='vinculado'?'warn':''}">${STATUS_VOLUME[v.status]}</span></label>`).join('')||'<div class="empty">Nenhum volume encontrado.</div>'}</div></section>${sel.length?`<div class="selection-bar"><strong>${sel.length} volume(s)</strong><span>${pieces} peças · ${kg(weight)} kg</span><button class="btn btn-primary" data-action="form-lot">Criar lote de Pintura</button></div>`:''}`;}
function lotFilter(force=false){const f=ui.filters,q=f.busca.toLowerCase();return db.lotes.filter(l=>(!force||(l.status==='finalizado'))&&(force||f.situacao==='todos'||(f.situacao==='ativos'?l.status==='ativo':l.status==='finalizado'))&&(f.etapa==='todas'||l.etapaAtual===f.etapa)&&(f.prioridade==='todas'||l.prioridade===f.prioridade)&&(!q||[l.numero,l.cliente,l.pedido,l.perfil,l.cor].join(' ').toLowerCase().includes(q)));}
function filters(){return`<div class="toolbar"><input class="input" data-filter="busca" placeholder="Lote, cliente, pedido, perfil ou cor" value="${esc(ui.filters.busca)}"><select class="input" data-filter="etapa"><option value="todas">Todas as etapas</option>${ETAPAS.map(e=>`<option value="${e.id}" ${ui.filters.etapa===e.id?'selected':''}>${e.label}</option>`).join('')}</select><select class="input" data-filter="prioridade"><option value="todas">Todas as prioridades</option>${PRIORIDADES.map(p=>`<option ${ui.filters.prioridade===p?'selected':''}>${p}</option>`).join('')}</select><select class="input" data-filter="situacao"><option value="todos">Todos</option><option value="ativos" ${ui.filters.situacao==='ativos'?'selected':''}>Ativos</option><option value="finalizados" ${ui.filters.situacao==='finalizados'?'selected':''}>Finalizados</option></select></div>`;}
function tracking(){const ls=lotFilter();return`${head('Central de rastreamento','Da origem B08 ao resultado final.')}${stats()}<section class="panel"><div class="panel-head"><h2>${ls.length} lote(s)</h2></div>${filters()}${lotList(ls)}</section>`;}
function finished(){return`${head('Embalagem finalizada','Disponível para avaliação do PCP; não significa faturado.')}${lotList(lotFilter(true))}`;}
function lotList(ls){if(!ls.length)return'<div class="empty">Nenhum lote encontrado.</div>';return`<div class="lot-list">${ls.map(l=>`<article class="lot-row"><div class="lot-main"><span class="lot-id">${esc(l.numero)}</span><strong>${esc(l.perfil)} · ${esc(l.cor)}</strong><small>${l.quantidadeVolumes} volume(s) · ${esc(l.pedido)}</small></div><div class="client-cell"><strong>${esc(l.cliente)}</strong><small class="muted">Atualizado ${dt(l.atualizadoEm)}</small></div><div class="lot-stage"><strong><span>${esc(etapaLabel(l.etapaAtual))}</span><span>${progresso(l)}%</span></strong><div class="progress"><span style="width:${progresso(l)}%"></span></div></div><div class="qty"><strong>${l.pecasAtuais}</strong><small>peças · ${kg(l.kgAtual)} kg</small></div><div class="priority-cell"><span class="priority ${l.prioridade}">${l.prioridade}</span><button class="btn btn-secondary btn-sm" style="margin-top:7px" data-detail="${l.id}">Abrir</button></div><button class="btn btn-secondary btn-sm mobile-only" data-detail="${l.id}">Abrir</button></article>`).join('')}</div>`;}
function detail(){const l=lot(ui.selected);if(!l)return dashboard();const ts=temposLote(l),next={formado:'Receber na Pintura',recebido:'Iniciar montagem',processo:'Finalizar embalagem'}[l.etapaAtual],vols=l.volumeIds.map(id=>db.volumes.find(v=>v.id===id)).filter(Boolean);return`${head(`${esc(l.numero)} · ${esc(l.cliente)}`,`${l.quantidadeVolumes} volume(s) · ${esc(l.cor)}`,'')}<button class="btn btn-secondary btn-sm" data-view="rastreio">← Voltar</button><div style="height:12px"></div><section class="panel"><div class="macro-flow">${ETAPAS.map((e,i)=>`<div class="flow-step ${i<ETAPAS.findIndex(x=>x.id===l.etapaAtual)?'done':e.id===l.etapaAtual?'current':''}"><div class="num">${e.operational?'MARCO OPERACIONAL':'ORIGEM'}</div><div class="name">${e.label}</div></div>`).join('')}</div></section><div style="height:16px"></div><div class="detail-grid"><section class="panel"><div class="panel-head"><h2>Linha do tempo</h2><span class="muted">${events(l.id).length} registros preservados</span></div>${timeline(l)}</section><div><section class="panel"><div class="panel-head"><h2>Indicadores do lote</h2></div><div class="summary">${sum('Volumes B08',l.quantidadeVolumes)}${sum('Peças B08',l.pecasB08)}${sum('Saldo/boas',l.pecasAtuais)}${sum('Peso atual',`${kg(l.kgAtual)} kg`)}${sum('Recebido em',dt(l.recebidoEm))}${sum('Início processo',dt(l.inicioProcessoEm))}${sum('Finalizado em',dt(l.finalizadoEm))}${sum('Tempo processo',duration(ts.processoMs))}${sum('Espera',duration(ts.esperaMs))}${sum('Total no setor',duration(ts.totalSetorMs))}${sum('Perdas',l.perdasAcumuladas)}${sum('Retrabalho',l.retrabalhoAcumulado)}</div></section>${next?`<button class="btn btn-primary" style="width:100%;margin-top:12px" data-advance="${l.id}">${next}</button>`:''}</div></div><div style="height:16px"></div><section class="panel"><div class="panel-head"><h2>Volumes de origem</h2></div>${volumesMini(vols)}</section>`;}
const sum=(a,b)=>`<div class="summary-item"><span>${a}</span><strong>${esc(b)}</strong></div>`;
function volumesMini(vs){return`<div class="b08-table">${vs.map(v=>`<div class="b08-row" style="grid-template-columns:1fr 1fr 1fr 1fr"><span><strong class="mono">${v.volume}</strong><small>${v.pedido} · item ${v.item}</small></span><span>${esc(v.ferramenta)}<small>${esc(v.beneficiamento)}</small></span><span>${v.pecas} peças<small>${kg(v.pesoLiquido)} kg</small></span><span>Embalado ${esc(v.dataEmbalagem)}</span></div>`).join('')}</div>`;}
function timeline(l){return`<div class="timeline">${events(l.id).map(e=>`<div class="event"><div class="event-icon">${e.tipo==='formacao'?'+':'✓'}</div><div class="event-body"><div class="event-title"><span>${esc(etapaLabel(e.para))}</span><span class="mono muted">${dt(e.criadoEm)}</span></div><div class="event-meta">Usuário: ${esc(e.usuario.nome)}</div><div class="event-qty"><span class="tag">${e.quantidadeVolumes||l.quantidadeVolumes} volume(s)</span><span class="tag">${e.pecas} peças</span><span class="tag">${kg(e.kg)} kg</span>${e.perda?`<span class="tag loss">Perda ${e.perda}</span>`:''}${e.retrabalho?`<span class="tag warn">Retrabalho ${e.retrabalho}</span>`:''}${e.divergencia?`<span class="tag warn">Divergência ${e.divergencia}</span>`:''}</div>${e.motivo?`<div class="issue"><strong>Motivo:</strong> ${esc(e.motivo)}</div>`:''}</div></div>`).join('')}</div>`;}
function issues(){const es=db.eventos.filter(e=>e.perda||e.retrabalho||e.divergencia);return`${head('Central de divergências','Ocorrências preservadas por lote e movimentação.')}<section class="panel"><div class="timeline">${es.map(e=>{const l=lot(e.loteId);return`<div class="event"><div class="event-icon">!</div><div class="event-body"><div class="event-title"><button class="btn btn-secondary btn-sm" data-detail="${l.id}">${esc(l.numero)}</button><span>${dt(e.criadoEm)}</span></div><div class="event-qty">${e.perda?`<span class="tag loss">Perda ${e.perda}</span>`:''}${e.retrabalho?`<span class="tag warn">Retrabalho ${e.retrabalho}</span>`:''}${e.divergencia?`<span class="tag warn">Divergência ${e.divergencia}</span>`:''}</div><div class="issue">${esc(e.motivo)}</div></div></div>`}).join('')||'<div class="empty">Nenhuma ocorrência.</div>'}</div></section>`;}
function consumption(){return`${head('Consumo de tinta','Estrutura reservada para evolução futura.')}<section class="panel"><div class="consumption"><div class="placeholder">Esta etapa continua apenas preparada. Nenhuma integração ou regra de estoque foi iniciada.</div></div></section>`;}
function shell(title,body){return`<div class="modal-backdrop" data-action="close"><section class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>${title}</h2><button class="close" data-action="close">×</button></div>${body}</section></div>`;}
function field(n,l,v,type='number',attrs=''){return`<div class="field"><label>${l}</label><input class="input" name="${n}" type="${type}" value="${esc(v)}" ${attrs}></div>`;}
function actors(){return`<div class="field"><label>Usuário responsável</label><select class="input" name="actor">${Object.entries(USERS).filter(([k])=>k!=='pcp').map(([k,a])=>`<option value="${k}">${a.nome}</option>`).join('')}</select></div>`;}
function modal(){if(ui.modal==='import'){return shell('Importar / atualizar B08',`<form id="import-form" class="form"><div class="placeholder">Aceita CSV e Excel (.xlsx/.xls). VOLUME é a chave de controle; reimportações são classificadas sem duplicação.</div><div class="field" style="margin-top:14px"><label>Arquivo B08</label><input class="input" type="file" name="file" accept=".csv,.xlsx,.xls" required></div>${ui.importResult?`<div class="issue">${esc(ui.importResult)}</div>`:''}${err()}<div class="form-actions"><button type="button" class="btn btn-secondary" data-action="close">Cancelar</button><button class="btn btn-primary">Importar / atualizar</button></div></form>`);}
 if(ui.modal==='formLot'){const vs=[...ui.selectedVolumes].map(id=>db.volumes.find(v=>v.id===id)).filter(Boolean);return shell('Criar lote de Pintura',`<form id="form-lot" class="form"><p><strong>${vs.length} volume(s)</strong> · ${vs.reduce((s,v)=>s+v.pecas,0)} peças · ${kg(vs.reduce((s,v)=>s+v.pesoLiquido,0))} kg</p><div class="form-grid">${field('numero','Número do lote','', 'text','placeholder="Automático"')}<div class="field"><label>Prioridade</label><select class="input" name="prioridade">${PRIORIDADES.map(p=>`<option>${p}</option>`).join('')}</select></div><div class="field span-2"><label>Observação</label><textarea class="input" name="observacao"></textarea></div></div>${err()}<div class="form-actions"><button type="button" class="btn btn-secondary" data-action="close">Cancelar</button><button class="btn btn-primary">Formar lote</button></div></form>`);}
 if(ui.modal==='advance'){const l=lot(ui.selected);return shell({formado:'Confirmar recebimento',recebido:'Iniciar montagem dos carrinhos',processo:'Finalizar embalagem'}[l.etapaAtual],advanceForm(l));}return'';
}
const err=()=>ui.error?`<div class="form-error">${esc(ui.error)}</div>`:'';
function advanceForm(l){let fields='';if(l.etapaAtual==='formado')fields=`${field('quantidadeVolumes','Volumes recebidos',l.quantidadeVolumes)}${field('pecas','Peças recebidas',l.pecasB08)}${field('kg','Kg recebidos',l.kgB08,'number','step="0.001"')}`;if(l.etapaAtual==='recebido')fields=`${field('pecas','Peças entrando em processo',l.pecasAtuais)}${field('kg','Kg entrando em processo',l.kgAtual,'number','step="0.001"')}`;if(l.etapaAtual==='processo')fields=`${field('pecasBoas','Peças boas',l.pecasAtuais)}${field('kg','Kg final',l.kgAtual,'number','step="0.001"')}${field('perda','Perda definitiva',0)}${field('retrabalho','Retrabalho',0)}${field('divergencia','Divergência de contagem',0)}`;return`<form id="advance-form" class="form"><p class="muted">Referência atual: ${l.pecasAtuais} peças · ${kg(l.kgAtual)} kg.</p><div class="form-grid">${fields}${actors()}<div class="field span-2"><label>Motivo da diferença</label><input class="input" name="motivo" placeholder="Obrigatório quando houver diferença, perda ou retrabalho"></div><div class="field span-2"><label>Observação</label><textarea class="input" name="observacao"></textarea></div></div>${l.etapaAtual==='processo'?'<div class="equation">Entrada = boas + perda + retrabalho + divergência</div>':''}${err()}<div class="form-actions"><button type="button" class="btn btn-secondary" data-action="close">Cancelar</button><button class="btn btn-primary">Registrar marco</button></div></form>`;}
function bind(){app.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{ui.view=e.dataset.view;ui.modal=null;render();});app.querySelectorAll('[data-detail]').forEach(e=>e.onclick=()=>{ui.selected=e.dataset.detail;ui.view='detalhe';render();});app.querySelectorAll('[data-filter]').forEach(e=>e.oninput=()=>{ui.filters[e.dataset.filter]=e.value;render();});app.querySelectorAll('[data-action="close"]').forEach(e=>e.onclick=()=>{ui.modal=null;ui.error='';render();});app.querySelectorAll('[data-volume]').forEach(e=>e.onchange=()=>{e.checked?ui.selectedVolumes.add(e.dataset.volume):ui.selectedVolumes.delete(e.dataset.volume);render();});const imp=app.querySelector('[data-action="import"]');if(imp)imp.onclick=()=>{ui.modal='import';ui.error='';ui.importResult=null;render();};const form=app.querySelector('[data-action="form-lot"]');if(form)form.onclick=()=>{ui.modal='formLot';ui.error='';render();};app.querySelectorAll('[data-advance]').forEach(e=>e.onclick=()=>{ui.selected=e.dataset.advance;ui.modal='advance';ui.error='';render();});const f1=app.querySelector('#form-lot');if(f1)f1.onsubmit=submitLot;const f2=app.querySelector('#advance-form');if(f2)f2.onsubmit=submitAdvance;const fi=app.querySelector('#import-form');if(fi)fi.onsubmit=submitImport;}
function submitLot(e){e.preventDefault();try{const selected=[...ui.selectedVolumes].map(id=>db.volumes.find(v=>v.id===id)).filter(Boolean),r=formarLote(selected,fd(e.currentTarget),USERS.pcp);db={...db,volumes:db.volumes.map(v=>r.volumes.find(x=>x.id===v.id)||v),lotes:[r.lote,...db.lotes],eventos:[...db.eventos,r.evento]};ui.selectedVolumes.clear();ui.modal=null;ui.selected=r.lote.id;ui.view='detalhe';save('Lote formado com volumes B08 preservados.');}catch(x){ui.error=x.message;render();}}
function submitAdvance(e){e.preventDefault();try{const data=fd(e.currentTarget),user=USERS[data.actor]||USERS.operador,l=lot(ui.selected),r=l.etapaAtual==='formado'?registrarRecebimento(l,data,user):l.etapaAtual==='recebido'?iniciarProcesso(l,data,user):finalizarEmbalagem(l,data,user);db={...db,lotes:db.lotes.map(x=>x.id===l.id?r.lote:x),eventos:[...db.eventos,r.evento]};ui.modal=null;save(`${etapaLabel(r.lote.etapaAtual)} registrado.`);}catch(x){ui.error=x.message;render();}}
async function submitImport(e){e.preventDefault();try{const file=e.currentTarget.file.files[0];if(!file)throw new Error('Selecione um arquivo.');let rows;if(file.name.toLowerCase().endsWith('.csv'))rows=parseCsv(await file.text());else{if(!window.XLSX)throw new Error('Leitor Excel indisponível. Use CSV ou verifique sua conexão.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''});}const r=importarB08(db.volumes,rows),count=s=>r.resultado.filter(x=>x.situacao===s).length;db={...db,volumes:r.volumes,importacoes:[...(db.importacoes||[]),{id:`IMP-${Date.now()}`,arquivo:file.name,criadoEm:new Date().toISOString(),resultado:r.resultado}]};store.save(db);ui.importResult=`${count('NOVO')} novo(s), ${count('ATUALIZADO')} atualizado(s), ${count('JÁ IMPORTADO')} já importado(s), ${count('JÁ VINCULADO A LOTE')} vinculado(s).`;render();}catch(x){ui.error=x.message;render();}}
render();
