import{round}from'./model.js';
export const BENEFICIADOR_PINTURA='001533';
const aliases={volume:['volume','vol'],pedido:['pedido','ordem'],item:['item'],cliente:['cliente','tratamento cliente','tratamento/cliente'],dataEmbalagem:['data','data embalagem'],equipe:['equipe'],beneficiador:['beneficiador','cod beneficiador','código beneficiador'],ferramenta:['ferramenta','perfil'],amarra:['amarra'],pecas:['pecas','peças','qtd pecas','quantidade peças'],pesoLiquido:['peso liquido','peso líquido','kg','peso'],comprimento:['comprimento','corte'],beneficiamento:['beneficiamento','cor','codigo descricao beneficiamento','código/descrição de beneficiamento'],entrega:['entrega']};
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const num=v=>{let s=String(v??'').trim();if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0;};
const read=(row,names)=>{const keys=Object.keys(row);for(const n of names){const k=keys.find(x=>norm(x)===norm(n));if(k!==undefined)return row[k];}return'';};
// Hipótese exclusiva do protótipo. A chave definitiva A → P depende da validação da B08 real.
export const chaveMaterialProvisoria=v=>[v.pedido,v.item,v.ferramenta,v.beneficiamento].map(norm).join('|');
export const chaveMaterial=chaveMaterialProvisoria;
export const pertencePintura=v=>String(v?.beneficiador||'').padStart(6,'0')===BENEFICIADOR_PINTURA;
export const interpretarEquipe=v=>String(v?.equipe||'').trim().toUpperCase()==='P'?'PINTADO_ACESYS':String(v?.equipe||'').trim().toUpperCase()==='A'?'FILA_PINTURA':'EQUIPE_NAO_MAPEADA';
export function normalizeB08Row(row){const volume=String(read(row,aliases.volume)||'').trim();if(!volume)return null;const equipe=String(read(row,aliases.equipe)||'').trim().toUpperCase(),beneficiador=String(read(row,aliases.beneficiador)||'').trim().padStart(6,'0');const v={id:`B08-${volume}`,volume,pedido:String(read(row,aliases.pedido)||'').trim(),item:String(read(row,aliases.item)||'').trim(),cliente:String(read(row,aliases.cliente)||'').trim(),dataEmbalagem:String(read(row,aliases.dataEmbalagem)||'').trim(),equipe,beneficiador,ferramenta:String(read(row,aliases.ferramenta)||'').trim(),amarra:String(read(row,aliases.amarra)||'').trim(),pecas:num(read(row,aliases.pecas)),pesoLiquido:round(num(read(row,aliases.pesoLiquido))),comprimento:String(read(row,aliases.comprimento)||'').trim(),beneficiamento:String(read(row,aliases.beneficiamento)||'').trim(),entrega:String(read(row,aliases.entrega)||'').trim(),camposOriginais:{...row},status:'disponivel',loteId:null};return{...v,chaveMaterial:chaveMaterialProvisoria(v),interpretacaoEquipe:interpretarEquipe(v),confirmadoAcesys:equipe==='P'};}
const changed=(a,b)=>['pedido','item','cliente','dataEmbalagem','equipe','beneficiador','ferramenta','pecas','pesoLiquido','comprimento','beneficiamento','entrega'].some(k=>String(a[k]??'')!==String(b[k]??''));
export function importarB08(existing,rows,now=new Date().toISOString()){
 const map=new Map(existing.map(v=>[v.volume,v])),resultado=[],stats={totalLidos:0,pintura:0,ignorados:0,novos:0,atualizados:0,conhecidos:0};
 for(const raw of rows){const incoming=normalizeB08Row(raw);if(!incoming)continue;stats.totalLidos++;if(!pertencePintura(incoming)){stats.ignorados++;resultado.push({volume:incoming.volume,situacao:'IGNORADO — FORA DA PINTURA'});continue;}stats.pintura++;const old=map.get(incoming.volume);
  if(!old){Object.assign(incoming,{importadoEm:now,atualizadoEm:now,historicoB08:[{em:now,equipe:incoming.equipe,pesoLiquido:incoming.pesoLiquido}]});map.set(incoming.volume,incoming);stats.novos++;resultado.push({volume:incoming.volume,situacao:'NOVO'});continue;}
  if(changed(old,incoming)){const history=[...(old.historicoB08||[]),{em:now,equipe:incoming.equipe,pesoLiquido:incoming.pesoLiquido}];map.set(old.volume,{...old,...incoming,id:old.id,importadoEm:old.importadoEm,atualizadoEm:now,status:old.status,loteId:old.loteId,historicoB08:history});stats.atualizados++;resultado.push({volume:old.volume,situacao:'ATUALIZADO'});}else{stats.conhecidos++;resultado.push({volume:old.volume,situacao:'JÁ CONHECIDO'});}
 }
 const volumes=[...map.values()];const pKeys=new Set(volumes.filter(v=>v.equipe==='P').map(chaveMaterialProvisoria));for(const v of volumes)if(v.equipe==='A')v.confirmadoAcesys=pKeys.has(chaveMaterialProvisoria(v));
 return{volumes,resultado,stats,importacao:{id:`IMP-${Date.now()}`,criadoEm:now,stats,resultado}};
}
export function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());if(!lines.length)return[];const delimiter=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const parse=line=>{const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='\"'){if(quoted&&line[i+1]==='\"'){cur+='\"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out;};const headers=parse(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(parse(line).map((v,i)=>[headers[i]||`COL_${i+1}`,v])));}
